from enum import Enum

class ErrorCode(str, Enum):
    # Nova Act Failures
    SELECTOR_NOT_FOUND = "SELECTOR_NOT_FOUND"
    AUTH_FAILED = "AUTH_FAILED"
    RATE_LIMITED = "RATE_LIMITED"
    TIMEOUT = "TIMEOUT"
    INVALID_JSON_RESPONSE = "INVALID_JSON_RESPONSE"
    BROWSER_CRASH = "BROWSER_CRASH"
    
    # Generic Failures
    SYSTEM_ERROR = "SYSTEM_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    UNAUTHORIZED = "UNAUTHORIZED"
